package Paths;
use Exporter ();
@ISA    = qw(Exporter);
@EXPORT = qw($LOCKERDIR $LOCKDIR $ETCDIR $MAILDIR $YPMASTER $ALIASESDIR $CREDDIR);
$YPMASTER = "rm-rstar1.sfu.ca";
$LOCKERDIR="/opt/adm/amaint";
$LOCKDIR="/opt/adm/amaintlocks";
$ETCDIR="/opt/amaint/etc";
$PUBBINDIR="/opt/bin";
$MAILDIR="/opt/mail";
$ALIASESDIR="/opt/mail";
$CREDDIR="/usr/local/credentials/";
