package Paths;
use Exporter ();
@ISA    = qw(Exporter);
@EXPORT = qw($LOCKERDIR $LOCKDIR $ETCDIR $BINDIR $MAILDIR $ALIASESDIR $CREDDIR $MAILLISTDIR);
$LOCKERDIR="/opt/mail/amaint/var";
$LOCKDIR="/opt/mail/amaint/var/amaintlocks";
$ETCDIR="/opt/mail/amaint/etc";
$BINDIR="/opt/mail/amaint/prod/bin";
$LIBDIR="/opt/mail/amaint/prod/lib";
$PUBBINDIR="/opt/bin";
$MAILDIR="/opt/mail";
$ALIASESDIR="/opt/mail";
$CREDDIR="/opt/credentials/";
$MAILLISTDIR="$MAILDIR/maillist2";
