package Paths;
use Exporter ();
@ISA    = qw(Exporter);
@EXPORT = qw($LOCKERDIR $LOCKDIR $ETCDIR $BINDIR $MAILDIR $ALIASESDIR $CREDDIR $MAILLISTDIR);
$LOCKERDIR="/opt/adm/amaint";
$LOCKDIR="/opt/adm/amaintlocks";
$ETCDIR="/opt/amaint/etc";
$BINDIR="/opt/amaint/maillist/bin";
$LIBDIR="/opt/amaint/maillist/lib";
$PUBBINDIR="/opt/bin";
$MAILDIR="/opt/mail";
$ALIASESDIR="/opt/mail";
$CREDDIR="/usr/local/credentials/";
$MAILLISTDIR="$MAILDIR/maillist2";
